alias chrome='open -a "Google Chrome"'
chrome="Chrome"
alias photoshop='open -a "Adobe Photoshop CS5"'
photoshop="Adobe Photoshop CS5"
alias firefox='open -a "FireFox"'
firefox="FireFox"
alias activity_monitor='open -a "Activity Monitor"'
activity_monitor="Activity Monitor"
alias mail='open -a Mail'
mail="Mail"
alias safari='open -a Safari'
safari="Safari"
alias transmission="open -a Transmission"
transmission='open -a Transmission'
alias preview='open -a "Preview"'
pages='open -a "Pages"'
alias pages='${pages}'

alias sublime.restart='killall "Sublime Text 2" && open -a "Sublime Text 2"'