runtime bundle/vim-pathogen/autoload/pathogen.vim

" initialize pathogen to help with bundles
execute pathogen#infect()

" support syntax coloring
syntax on

"help with file types
filetype plugin indent on
filetype plugin on

" enable nerdtree support each time we initialize vim
"autocmd vimenter * if !argc() | NERDTree | endif

syntax enable
set background=dark

let g:solarized_termcolors=256
colorscheme solarized
"colors monokai
let g:molokai_original = 1
"initialize vim settings
" make buffers hide instead of close
set hidden

"don't wrap lines
set nowrap

"Set the vim clipboard
set clipboard=unnamed
set autoindent
set copyindent
"always show the line numbers
set number
"show matching parenthesis
set showmatch
set ignorecase
set smartcase
set smarttab
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.ds_store,*.pyc,*.class
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
"Set the file type live ... :set filetype=cpp
"set the directory to automatically change to the working directory when using vim
"set autochdir
"initialize wildignore for various files with command-t

set wildignore+=*.o,*.obj,.git,node_modules
