"load up our bundle loaders!
runtime bundle/vim-pathogen/autoload/pathogen.vim

" initialize pathogen to help with bundles
execute pathogen#infect()

" support syntax coloring
syntax on

"help with file types
filetype plugin indent on
filetype plugin on
" initialie files to autoignore with nerd-tree

"enable nerdtree support each time we initialize vim
"autocmd vimenter * if !argc() | NERDTree | endif
syntax enable

" Initialize color scheme for application
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
"colors monokai
let g:molokai_original = 1


" make buffers hide instead of close
set hidden

"don't wrap lines
set nowrap

"Set the vim clipboard
set clipboard=unnamed

set autoindent
set copyindent
"always show the line numbers
set number
"show matching parenthesis
set showmatch
set ignorecase
set smartcase
set smarttab
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.ds_store,*.pyc,*.class
set wildignore+=*.o,*.obj,.git,node_modules
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile

" set whther or not to highlight searches
"set nohlsearch
"http://vim.wikia.com/wiki/Mac_OS_X_clipboard_sharing:
" now create a command to clear the highlighting
command C let @/=""

" set up some mac copy paste elements
command -range Y w !pbcopy
command -range P r !pbpaste

" set up and alias to help with saving
command W w
