SHELL=/usr/local/bin/zsh
ZSH=$HOME/.oh-my-zsh

plugins=(brew)

ZSH_THEME="zshell-theme.zsh"
ZSH_CUSTOM=$HOME/dotfiles/helpers
MY_ZSH_THEME=$ZSH_THEME; ZSH_THEME=''

# OH MY ZSH!
source $ZSH/oh-my-zsh.sh
 
# Github issue: https://github.com/robbyrussell/oh-my-zsh/pull/1107
source "$ZSH_CUSTOM/$MY_ZSH_THEME"

# Uncomment following line if you want to disable colors in ls
DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Zshell specific options
unsetopt cdablevarS
unsetopt correct_all

# source our bash core 
source $HOME/dotfiles/core.sh

compctl -k "()" brew install

# stop all autocorrection
unsetopt correct_all
# set up the vim keyword mode for zsh
bindkey -v

# now lets set up our history searching for forward / reverse searching
bindkey '^R' history-incremental-search-backward

# history settings
setopt hist_ignore_all_dups
setopt hist_ignore_space





