source 'https://rubygems.org'

# global requirements
gem 'rails', '3.2.12'
# enable active model 4.0 for this build
# mongodb is our primary database in the application
gem 'mongoid', '~> 3.0.0'
# enable active model for this particular application
# initialize rake for all tasks related to the application etc
gem 'rake', '10.0.3'
####### API GEMS ########
# for now lets use the aws server to serve to our s3 buckets
# in the future check out the rightserve application https://github.com/rightscale/right_aws
gem 'aws', '~>2.8.0' 
# paper clip is useful for attaching s3 images / files onto active record models. We can abstract away our storage with this easily
gem 'paperclip', '~>3.4.1' 

##### SEARCHING / INDEXING --- ELASTIC SEARCH #####
# allow us to index directly from our rails application
gem 'tire', '~>0.5.4'

##### #NOTIFICATIONS / PUSH MESSAGES #######
# apple push notification services 
gem 'apns', '~>1.0.0'
#### FACTUAL BUSINESS API ######
gem 'factual-api', '~>1.3.4'

# authentication
# bcrypt is supposedly the best algorithm available right now
gem 'bcrypt-ruby', '~>3.0.1'
# to use this bcrypt -- look into devise configurable etc for this application

# facebook
gem 'omniauth-facebook', '~>1.4.1'
# twitter omniauth-library
gem 'omniauth-twitter','~>0.0.14'
# devise is for home-cooked authentication storing
gem 'devise', '>= 2.2.3'
# this is useful for easy environment variables etc
gem 'figaro', '>= 0.5.3'
# cancan is for authentication access controls -- ie ... setting up admins etc
gem 'cancan', '~> 1.6.9'
# add rolify to help us define roles for our users etc
gem 'rolify', '~> 3.2.0'

gem 'amico'
####### ASSETS / FRONT END BASED GEMS #########
#use haml templating
gem 'haml', '4.0.0'
# add haml scaffolding support for application during test
gem 'haml-rails', :group => [:assets]

# want something to convert all of our existing erb templates -- the devise ones to haml
# this will allow us to initialize a rake test to help with this
gem 'erb2haml', '~> 0.1.4', :group => [:development]
gem 'html2haml', :group => [:development]

# asset  elements
# sass helper for rails asset pipeline
# gem 'sass-rails', '3.2.3', :group => [:assets]
# modernizr bundler for rails
# gem "compass", "~> 0.12.2", :group => [:assets]
# compass susy plugins
# gem 'compass-susy-plugin', "~> 0.9", :group => [:assets]	
# rails pipeline coffeescript compilers
# gem 'coffee-rails', '~> 3.2.1', :group => [:assets]
# uglifier to compress and mess up our javascript
# gem 'uglifier', '>= 1.0.3', :group => [:assets]
# initialize rails with require js 
# gem 'requirejs-rails', '~> 0.9.1', :group => [:assets]	

# javascript libraries
# for production, these will be modularized differently and will be included in a build process
# gem 'jquery-rails', '~> 2.2.1', :group => [:test, :development]
# gem 'backbone-rails', '~> 0.9.9', :group => [:test, :development]
# gem 'modernizr-rails', '~> 2.6.2', :group => [:test, :development]



# Test gems and helpers etc
# testing for rails using rspec
# not necessarily using rspec assertion testing etc for this application
# the business portal will use capybara style acceptance testing etc
# rspec will be used with some of the more complicated api requests
# hard testing will be performed with rspec for our hard api calls etc
gem 'rspec-rails', '>= 2.12.2', :group => [:development, :test]
# rest-client used to help with api tests etc throughout application
gem 'rest-client', :group => [ :development, :test ]
# datbase cleaner is for clearing the database between runs
gem 'database_cleaner', '>= 0.9.1', :group => :test
# email spec for testing email
gem 'email_spec', '>= 1.4.0', :group => :test
# cucumber units for rails
# gem 'cucumber-rails', '>= 1.3.0', :group => :test, :require => false
# launchy is useful for launching applications across your machine using rails
# not being used currently 
# gem 'launchy', '~> 2.2.0', :group => :test
# helps you simulate how a user works on your application https://github.com/jnicklas/capybara
# gem 'capybara', '>= 2.0.2', :group => :test
# using this instead of the selenium style of browser mimicing etc
# gem 'capybara-webkit'
# use this for factory creation of objects needed for tdd etc
gem 'factory_girl_rails', '>= 4.2.0', :group => [:development, :test]
# helps prevent assets from being used / compiled during development?
# gem 'quiet_assets', '>= 1.0.1', :group => :development
# replaces the default rails error page with a more informative error page ... 
gem 'better_errors', '>= 0.3.2', :group => :development
# allows use to grb variable bindings from higher up
gem 'binding_of_caller', '>= 0.6.8', :group => :development

# development tools
# intialize pretty print for printing objects in the console with good formatting
gem 'awesome_print', :group => :development 
# initialize wirble for enhanced irb support
gem 'wirble', :group => :development

